local config = require("obscure.config")
local p = require("obscure.palette")

local styles = vim.tbl_map(function(value)
  return setmetatable(value, {
    __add = function(a, b)
      return vim.tbl_extend("force", a, b)
    end,
  })
end, config.styles)

return {
  ["@annotation"] = { link = "PreProc" },
  ["@attribute"] = { link = "PreProc" },
  ["@boolean"] = { link = "Boolean" } + styles.booleans,
  ["@character"] = { link = "Character" },
  ["@character.special"] = { link = "SpecialChar" },
  ["@comment"] = { link = "Comment" },
  ["@comment.error"] = { fg = p.red },
  ["@comment.hint"] = { fg = p.cyan },
  ["@comment.info"] = { fg = p.purple },
  ["@commnet.note"] = { fg = p.cyan },
  ["@comment.todo"] = { fg = p.blue },
  ["@comment.warning"] = { fg = p.yellow },
  ["@constant"] = { link = "Constant" },
  ["@constant.builtin"] = { link = "Special" },
  ["@constructor"] = { fg = p.subtext1 },
  ["@constructor.tsx"] = { fg = p.blue },
  ["@namespace"] = { fg = p.red, italic = true },
  ["@parameter"] = { fg = p.magenta },
  ["@property"] = { fg = p.orange },
  ["@punctuation"] = { fg = p.subtext1 },
  ["@punctuation.delimiter"] = { fg = p.subtext1 },
  ["@punctuation.bracket"] = { fg = p.subtext1 },
  ["@punctuation.special"] = { fg = p.subtext1 },
  ["@string.documentation"] = { fg = p.green } + styles.comments,
  ["@string.regex"] = { fg = p.purple },
  ["@string.escape"] = { fg = p.magenta },
  ["@symbol"] = { fg = p.yellow },
  ["@tag"] = { fg = p.red },
  ["@tag.attribute"] = { fg = p.bright_purple, italic = true },
  ["@tag.delimiter"] = { fg = p.subtext1 },
  ["@type.builtin"] = { fg = p.magenta },
  ["@variable"] = { fg = p.fg } + styles.variables,
  ["@variable.builtin"] = { fg = p.purple } + styles.variables,
  ["@variable.parameter"] = { fg = p.magenta } + styles.variables,
  ["@constructor.javascript"] = { fg = p.red },
  ["@function"] = { link = "Function" },
  ["@function.builtin"] = { link = "Special" },
  ["@function.call"] = { link = "@function" },
  ["@function.macro"] = { link = "Macro" },
  ["@function.method"] = { link = "Function" },
  ["@function.method.call"] = { link = "@function.method" },
  ["@keyword"] = { fg = p.purple } + styles.keywords, -- For keywords that don't fall in previous categories. purple
  ["@keyword.conditional"] = { link = "Conditional" },
  ["@keyword.coroutine"] = { link = "@keyword" },
  ["@keyword.debug"] = { link = "Debug" },
  ["@keyword.clojure"] = { fg = p.bright_red } + styles.keywords,
  ["@keyword.function"] = { fg = p.purple } + styles.functions,
  ["@keyword.import"] = { link = "Include" },
  ["@keyword.storage"] = { link = "StorageClass" },
  ["@text.underline"] = { link = "Underlined" },
  ["@text.strong"] = { bold = true },
  ["@text.strikethrough"] = { strikethrough = true },
  ["@text.italic"] = { italic = true },
  ["@module"] = { link = "Include" },
  ["@module.builtin"] = { fg = p.purple },
  ["@markup.heading"] = { fg = p.fg, bold = true },
  ["@markup.heading.1"] = { fg = p.blue, bold = true },
  ["@markup.heading.1.marker"] = { link = "@comment" },
  ["@markup.heading.2"] = { fg = p.blue, bold = true },
  ["@markup.heading.2.marker"] = { link = "@comment" },
  ["@markup.heading.3"] = { fg = p.blue, bold = true },
  ["@markup.heading.3.marker"] = { link = "@comment" },
  ["@markup.heading.4"] = { fg = p.blue, bold = true },
  ["@markup.heading.4.marker"] = { link = "@comment" },
  ["@markup.heading.5"] = { fg = p.blue, bold = true },
  ["@markup.heading.5.marker"] = { link = "@comment" },
  ["@markup.heading.6"] = { fg = p.blue, bold = true },
  ["@markup.heading.6.marker"] = { link = "@comment" },
  ["@markup.link"] = { fg = p.subtext1 },
  ["@markup.link.label"] = { fg = p.red },
  ["@markup.link.url"] = { fg = p.purple },
  ["@markup.list"] = { fg = p.subtext4, bold = true },
  ["@markup.list.checked"] = { fg = p.subtext4 },
  ["@markup.list.unchecked"] = { fg = p.subtext4 },
  ["@markup.raw.block"] = { fg = p.subtext4 },
  ["@markup.raw.delimiter"] = { fg = p.subtext4 },
  ["@markup.quote"] = { fg = p.subtext1 },
  ["@markup.list.checked.markdown"] = { fg = p.green },
  ["@markup.underline"] = { link = "@text.underline" },
  ["@markup.strong"] = { link = "@text.strong" },
  ["@markup.italic"] = { link = "@text.italic" },
  ["@markup.strikethrough"] = { link = "@text.strikethrough" },
}
